services:
  api:
    build: .
    command: 'fastapi dev app/main.py --host=0.0.0.0 --port=8000'
    tty: true
    depends_on:
      - db
    links:
      - db
    logging:
      options:
        max-file: "1"
        max-size: 1m
    ports:
      - 8000:8000
    volumes:
      - .:/sync
    working_dir: "/sync"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "sqlmodel_example"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
